### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by junipertcy** [marcoguerra192/MinScaffold#1]
Hi @marcoguerra192,

Congrats on making the repository public! I have been looking forward to it since seeing your arXiv paper and Master thesis. However, without a license file, I cannot move forward and make proper use of the code. Could you add a license file to the repo? Thank you!

-tc

**Comment by marcoguerra192** [comment]
Hi @junipertcy, thanks for pointing this out, I'd quite forgotten! Happy coding!
Marco
